version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: nanoid
    versions:
    - 3.1.20
    - 3.1.21
  - dependency-name: lodash
    versions:
    - 4.17.20
